filter rspamd proc-exec "filter-rspamd"
pki horse.pcarrier.com cert "/etc/letsencrypt/live/horse.pcarrier.com/fullchain.pem"
pki horse.pcarrier.com key "/etc/letsencrypt/live/horse.pcarrier.com/privkey.pem"
listen on 0.0.0.0 port 25 tls pki horse.pcarrier.com filter "rspamd"
listen on 0.0.0.0 port 587 tls-require pki horse.pcarrier.com auth filter "rspamd"
listen on lo port 10587 filter "rspamd"
table virtuals { "@cc.me" = cc-me }
action "mail" mda "/usr/bin/env DATABASE_URL=postgres:///cc-me?host=/var/run/postgresql CC_ME_PUBLIC_URL=https://cc.me CC_ME_SMTP=127.0.0.1:10587 /usr/local/bin/cc-me-mail %{rcpt} %{sender}" virtual <virtuals>
action "outbound" relay
match from any for domain "cc.me" action "mail"
match from src 127.0.0.1/32 for any action "outbound"
match from local for any action "outbound"
